### ISSUE TITLE
`schemaUrl` it sends a few requests to the same resource

### ISSUE THREAD

**Issue by rols2015** [asyncapi/asyncapi-react#243] opened 2021-01-27 15:29 UTC
Hello guys, one more question: @aeworxet @derberg @magicmatatjahu 
when I use `schemaUrl` it sends a few requests to the same resource
![image](https://user-images.githubusercontent.com/16349586/105893231-d5403500-5fe0-11eb-9398-f3ea1ac7d5a0.png)

Also when I use my own api to get asyncAPI json the following message is shown until I get a response.
![image](https://user-images.githubusercontent.com/16349586/105905292-4509ec00-5ff0-11eb-94a8-8af433361ed6.png)
Can the `asyncapi-component` be rendered once url/json is parsed?

**Comment by derberg** [comment] 2021-01-27 20:01
The problem with multiple component rendering seems to know to the package that we use to build the web component -> https://github.com/ChristophP/web-react-components/issues/45

but the problem is that `web-react-components` doesn't seem to be actively developed. Last release `Sep 15, 2017` 🤔 

It will take time to solve...

> Can the asyncapi-component be rendered once url/json is parsed?

the only quick solution I see for not, if this additional fetching is a problem (at the end all those additional requests are actually cached) then you can just not use `schemaUrl` but `schema`, and fetch the spec on your own instead of counting on the component to do it. Thoughts?

**Comment by rols2015** [comment] 2021-01-27 21:35
I really like `shemaUrl`.
can for instance the event `onReady` be added for this component? So I can show when it's rendered.

**Comment by rols2015** [comment] 2021-01-27 21:48
@derberg actually your suggestion works perfectly as well.
```javascript
 element.setAttribute('schema', JSON.stringify(json));
```
Thank you so much

**Comment by derberg** [comment] 2021-01-27 21:51
no worries, I like `schemaUrl` too, especially that I wanted it 😄 
I'm not saying we will not fix it. Thing is that it needs to be fixed in dependency that is not actively developed so it will take us time to contact them and work it out but for sure we need to do this and I definitely do not want us to close this issue

**Comment by derberg** [comment] 2021-03-29 10:51
I'm afraid we will have to research for a different react2webcomponent converter. Something like https://github.com/bitovi/react-to-webcomponent that has maintainers

**Comment by magicmatatjahu** [comment] 2021-09-20 09:10
@AceTheCreator I know you are interested in this issue. Should I assign you to it? It doesn't mean you have to implement it right now, just for information.

**Comment by AceTheCreator** [comment] 2021-09-20 09:40
@magicmatatjahu Please assign it to me

**Comment by magicmatatjahu** [comment] 2022-01-13 11:16
@AceTheCreator Hi! I created PR with fix for that. I hope you don't mind :)

**Comment by AceTheCreator** [comment] 2022-01-17 08:42
> @AceTheCreator Hi! I created PR with fix for that. I hope you don't mind :)

It's fine @magicmatatjahu

**Comment by magicmatatjahu** [comment] 2022-01-17 09:29
Handled by https://github.com/asyncapi/asyncapi-react/pull/511

**Closed by magicmatatjahu** 2022-01-17 09:29 UTC
Labels: good first issue, Hacktoberfest, released on @next
