### ISSUE TITLE
Add internal webpage anchors (or produce a guide to show users how to enable)

### ISSUE THREAD

**Issue by joehandzik** [asyncapi/asyncapi-react#70] opened 2019-09-18 14:41 UTC
**Description**

The 0.3.0 component is a big improvement in usability. However, another feature that would significantly improve usability of this page as a primary documentation component for an API is  the ability to directly link to a specific component on the page.

**Reasons**

While the collapsable nesting has solved some navigation problems, it would still be ideal for documentation external to the core API page one creates with this component to have access to direct linking to a specific message/object/etc. For example, consider an external word document with more details around an application's design. To avoid reproducing pieces of the API outside of a page generated with this component, one could directly link to part of the page instead.

If this is already possible, a tutorial would be great! My personal perspective is that if this is possible, it should be enabled by default.

**Attachments**

**Comment by magicmatatjahu** [comment] 2019-09-18 18:25
@joehandzik Hello :) Thanks for using our component! It is a pleasure to hear that more and more people are using the component. However, I must sadden you, because we don't have any anchors attached to the component yet, which means that it is not possible to link to the appropriate components/data, but this isn't a hard to implement - of course if you mean about anchors like `{your-page}#{name-of-async-api-schema}-{name-of-message/channel/server}`. Also component doesn't have plugins system yet (but we thinking about it, like in SwaggerUI, but with more customisation), so enhancement for now must be done internally in component.

**Comment by joehandzik** [comment] 2019-09-20 21:30
I think you understand my request correctly, yes! I'm happy to help if my assistance can be useful.

**Comment by magicmatatjahu** [comment] 2019-09-24 13:13
@joehandzik I created PR with implementation of your suggestion. I also created pack for you - if you want install and test in your app/project, please install component by adding in package.json `"@kyma-project/asyncapi-react": "https://github.com/magicmatatjahu/asyncapi-react/raw/anchors/library/kyma-project-asyncapi-react-0.3.0.tgz"`, because at the moment, this feature is on work in progress, and if you'll like it and it'll work, we'll merge it :) [Here](https://github.com/magicmatatjahu/asyncapi-react/blob/anchors/docs/features/anchors.md) is also documentation, how it works :) Enjoy!

**Comment by joehandzik** [comment] 2019-09-24 14:34
First off, thank you very much for the help here. It may have been easy for you to make these changes, but it would have taken me a while to figure it out. :)

I just tested this on my end. A few documentation comments:

1. Probably worth describing that the default schemaID is 'asyncapi'. I had to dig through some documentation to figure that out, but it would make sense to flag that here as well.
2. It would have been helpful to reinforce the url format of http://{url}/#{NAME_OF_SCHEMA}--{CONTAINER|ITEM}--{ITEM_NAME}--{ITEM_PROPERTY} . Again, something that one can figure out by looking at the code and playing with the url a bit, but it would have saved a few minutes.

As for functionality itself, I was able to see this format work:

http://{url}/#{NAME_OF_SCHEMA}--{CONTAINER}

However, when I do something like either of these:

http://{url}/#{NAME_OF_SCHEMA}--{ITEM}--{ITEM_NAME}
http://{url}/#{NAME_OF_SCHEMA}--{ITEM}--{ITEM_NAME}--{ITEM_PROPERTY}

It doesn't seem to work quite right. An exact example url for my use case:

http://localhost:3000/#asyncapi--message--storageRegisterNamespace
http://localhost:3000/#asyncapi--message--storageRegisterNamespace--payload

The messages section opens up on the page, but it does not open up the specific message, nor does it scroll down to the specific message (in either case).

Let me know if you need/want more debug information from me. Again, thank you for your help.

**Comment by magicmatatjahu** [comment] 2019-09-26 12:48
@joehandzik Sorry for late response, but I had to resolve a few problems in component after introduce internal anchors, mostly with global component state. I updated docs with your suggestions, thanks for that! 

You wrote that:
```
It doesn't seem to work quite right. An exact example url for my use case:

http://localhost:3000/#asyncapi--message--storageRegisterNamespace
http://localhost:3000/#asyncapi--message--storageRegisterNamespace--payload
```

In previous implementation title of message had to be kebabcased, so corrected url would be  `http://localhost:3000/#asyncapi--message--storage-register-namespace`, but from now you can use `http://localhost:3000/#asyncapi--message--storageRegisterNamespace`. Please reinstall package and let me know, that everything is ok! :)

I tested behaviour in various schema and everything were good, but sometimes, when I played with toggles, then global state was acting strange, but with normal using, everything should be good.

**Comment by joehandzik** [comment] 2019-09-26 19:05
http://localhost:3000/#asyncapi--messages--storageRegisterNamespace works!
http://localhost:3000/#asyncapi--message--storageRegisterNamespace doesn't work

http://localhost:3000/#asyncapi--messages--storageRegisterNamespace--payload works!
http://localhost:3000/#asyncapi--message--storageRegisterNamespace--payload doesn't work

Looks like you updated the documentation to account for that, so it's all good. I, too, have noticed that the state doesn't clear on re-navigation. So doing this:

http://localhost:3000/#asyncapi--messages--storageRegisterNamespace

followed by this in the same page:

http://localhost:3000/#asyncapi--messages--storageRegisterNamespaceResponse

Results in both messages being open. Fortunately, the scrolling works right so the page reopens looking at the second command specified via url.

It's up to you if you want to leave this issue open or create new ones to track any state fixes you're going to try to implement. I'm pleased though, so feel free to close if that's your preferred workflow. Thank you!

**Comment by derberg** [comment] 2019-10-08 07:44
@joehandzik feature release under 0.3.1 and works like a charm. I bumped the version in our sandbox yesterday https://codesandbox.io/s/github/derberg/asyncapi-react-in-action/tree/master/?fontsize=14 and docs as you probably know are here https://github.com/asyncapi/asyncapi-react/blob/master/docs/features/anchors.md

I would close this issue for now. Feel free to create a new one in a case on any issues.
So far the fact that the previous components stay open when you decide to navigate to another one is not a bug imho. As you noticed, important is that scrolling works

**Closed by derberg** 2019-10-08 07:44 UTC
Labels: area/community, area/library, enhancement
